name: slide_extractor
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.5.0
  - blosc=1.21.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - c-blosc2=2.9.2
  - ca-certificates=2023.5.7
  - cairo=1.16.0
  - certifi=2023.5.7
  - cfitsio=4.2.0
  - charls=2.4.2
  - charset-normalizer=3.1.0
  - dav1d=1.2.0
  - expat=2.5.0
  - ffmpeg=6.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdbm=1.18
  - gettext=0.21.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.7.8
  - graphite2=1.3.13
  - harfbuzz=7.3.0
  - hdf5=1.14.0
  - icu=72.1
  - idna=3.4
  - imagecodecs=2023.1.23
  - imageio=2.28.1
  - jasper=4.0.0
  - joblib=1.2.0
  - jxrlib=1.1
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - lerc=4.0.0
  - libaec=1.0.6
  - libass=0.17.1
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.1.1
  - libcxx=16.0.4
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - libglib=2.76.3
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.52.0
  - libopenblas=0.3.21
  - libopencv=4.7.0
  - libopus=1.3.1
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - libsqlite=3.42.0
  - libssh2=1.10.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libvpx=1.13.0
  - libwebp-base=1.3.0
  - libxcb=1.15
  - libxml2=2.11.4
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=16.0.4
  - lz4-c=1.9.4
  - ncurses=6.3
  - nettle=3.8.1
  - networkx=3.1
  - numpy=1.24.3
  - opencv=4.7.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.1.0
  - p11-kit=0.24.1
  - packaging=23.1
  - pcre2=10.40
  - pillow=9.5.0
  - pip=23.1.2
  - pixman=0.40.0
  - platformdirs=3.5.1
  - pooch=1.7.0
  - pthread-stubs=0.4
  - py-opencv=4.7.0
  - pypy3.9=7.3.11
  - pysocks=1.7.1
  - python=3.9.16
  - python_abi=3.9
  - pywavelets=1.4.1
  - readline=8.2
  - requests=2.31.0
  - scikit-image=0.19.3
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - setuptools=67.7.2
  - snappy=1.1.10
  - sqlite=3.42.0
  - svt-av1=1.5.0
  - threadpoolctl=3.1.0
  - tifffile=2023.4.12
  - tk=8.6.12
  - typing-extensions=4.6.2
  - typing_extensions=4.6.2
  - tzdata=2023c
  - urllib3=2.0.2
  - wheel=0.40.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zfp=1.0.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.2
  - pip:
    - deprecation==2.1.0
    - img2pdf==0.4.4
    - lxml==4.9.2
    - pikepdf==7.2.0
    - tdqm==0.0.1
    - tqdm==4.65.0
